module.exports = {
    API_URL: 'api/v1/',
    APP_NAME: 'Facial Spotify Controller',
    COOKIE_NAME_SPOTIFY_ACCESS_TOKEN: 'SPOTIFY_ACCESS_TOKEN',
    COOKIE_NAME_SPOTIFY_REFRESH_TOKEN: 'SPOTIFY_REFRESH_TOKEN',
    COOKIE_NAME_SPOTIFY_AUTH_ERROR: 'SPOTIFY_AUTH_ERROR',
    SPOTIFY_API_URL: 'https://api.spotify.com/v1/me',
    SPOTIFY_WEB_PLAYBACK_SDK_SCRIPT_ID: 'spotify-web-playback-sdk-script',
    TF_BACKEND: 'cpu',
    EMOTION: {
        0: 'angry',
        1: 'disgust',
        2: 'fear',
        3: 'happy',
        4: 'sad',
        5: 'surprise',
        6: 'neutral',
    },
    CLASSIFIER_IMG_DIMENSIONS: [48, 48],
};