name: Deployment Workflow
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploying to intelligent-song-picker.com server via ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: aoede.uberspace.de
        username: kapaun
        key: ${{ secrets.ISP_SECRET }}
        port: 22
        script: |
          shopt -s extglob
          cd /var/www/virtual/kapaun/intelligent-song-picker.com/_repository/intelligent-song-picker/
          git pull
          git reset origin --hard
          yarn --cwd client install
          yarn --cwd client build
          rm -r ../../client/*
          cp -R client/dist/* ../../client
          rm -r ../../server/!(.env|node_modules)
          cp -R server/* ../../server
          yarn --cwd ../../server install
          supervisorctl restart isp_server
